version: '3'

services:
  spring:
    build: './'
    ports:
      - '8080:8080'
    environment:
      - DD_AGENT_HOST=datadog
      - DD_PROFILING_ENABLED=true

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=[your-key]
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro